<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHun8wjv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHun8wjv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHun8wjv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHun8wjv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHun8wjv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Hun8wjv',
    'container.build_id' => '0151be92',
    'container.build_time' => 1556014202,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHun8wjv');
